--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Aboshxm2/KDR2
build-by-default: true
branches:
- main
projects:
  KDR2:
    path: ""
    libs:
      ConfigUpdater:
        src: ifera-mc/ConfigUpdater/ConfigUpdater
        version: 2.0.0
      UpdateNotifier:
        src: ifera-mc/UpdateNotifier/UpdateNotifier
        version: 3.0.0
      libasynql:
        src: poggit/libasynql/libasynql
        version: 4.1.0
...
