name: KDR2
version: 1.1.1
author: Aboshxm2
api: 4.0.0
main: Aboshxm2\KDR2\Main

softdepend: ScoreHud

permissions:
  KDR2.commands.kdr.stats:
    default: true
  KDR2.commands.kdr.edit:
    default: op
